quarkus:
  # Logging
  log:
    console:
      enable: true
      json: true
    file:
      enable: true
      path: trace.log
      json: true
      level: ALL
    # Default log level
    level: INFO
    category:
      # Log level for package vn.tma
      "vn.tma":
        level: DEBUG


